### ISSUE TITLE
(v4.2) Undefined variable: $fa-enable-utilities

### ISSUE THREAD

**Issue by ProjectFrank** [cristianferrarig/font-awesome-middleman#12]
My font.scss file has only 1 line: 
`@import "font-awesome";`

This generates the following error in Middleman:
`Sass::SyntaxError at /
Undefined variable: "$fa-enable-utilities". (in /source/css/font.scss:1)`

The problem can be fixed by adding
`$fa-enable-utilities: true !default;`
to the beginning of font.scss which sets the variable to true (but you could also set it to false if that's what you need).

This problem occurred after updating middleman font-awesome to 4.2 after pull request from @trenton42  was merged. This problem did not occur in @trenton42 's version.

**Comment by trenton42** [comment]
After a year this somehow popped up and bit me again. I added `$fa-enable-utilities: true !default;` to _variables.scss, but I'm not sure if that is the right way to do it. If it is, I can make a PR.

**Comment by trenton42** [comment]
Looking through the update history, it looks like that variable had been removed then re-added, but the default was missing. PR'ed
